name: fernuni_discord_bot

services:
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    user: appuser:appuser
    env_file:
      - docker.env
    volumes:
      - ./data:/app/data
  scraper:
    build:
      context: .
      dockerfile: scraper.Dockerfile
    user: appuser:appuser
    volumes:
      - ./data:/app/data
  plotter:
    build:
      context: .
      dockerfile: plotter.Dockerfile
    user: appuser:appuser
    volumes:
      - ./data:/app/data  
      - ./data/plots:/app/results    